### ISSUE TITLE
Build failed with error Remotebuild requires your projects to use cordova-ios 4.3.0 or greater with XCode 8.3

### ISSUE THREAD

**Issue by TsunamiJohn** [Microsoft/remotebuild#47]
I am also getting the build error 'Build failed with error Remotebuild requires your projects to use cordova-ios 4.3.0 or greater with XCode 8.3.'. I tried reinstalling with sudo ('sudo npm install cordova@6.5.0'). I also tried 'sudo npm install cordova@7.0.0'. I also tried the chown command listed above. I reinstalled VS 2017, and upgraded to version 15.3. None of this works. I see in my config.xml that cordova-ios version 4.2 is being used. I don't see how to change/select version 4.3, which seems to be what is required.

Any idea what to try next ?

**Comment by rickmortensen** [comment]
On the mac I had to explicitly update the ios portion of Cordova:
https://stackoverflow.com/questions/44321757/how-to-update-cordova-ios-version-in-visual-studio-2015-cordova-project

**Comment by TsunamiJohn** [comment]
The issue is not on the mac, but in Visual Studio.  Visual studio wants to use cordova-ios version 4.2.0 (which is the version installed with and integrated with Visual Studio 2017).  Using cordova-ios version 4.2.0 on the Visual Studio side causes the error 'Build failed with error Remotebuild requires your projects to use cordova-ios 4.3.0 or greater with XCode 8.3'.  I globally installed cordova-ios 7.0.1 on my Visual Studio machine, and if I manually select this version in my config.xml, then the build error on the OSX side goes away (that is 7.0.1 is > 4.3.0, so the app builds, and deploys).  Now the issue is that every time I open the project in visual studio, I get the following error:

'Your Cordova project needs to be updated to work with Visual Studio'.  
If 'No' is chosen, the project is disabled and cannot be built or run.
If 'Yes' is chosen, the cordovia-ios version is set back to 4.2.0 (the version integrated with Visual Studio).   Once again, I get the osx build error.  Once again I have to manually set the visual studio cordova-ios version back to 7.0.1 in config.xml, and then it works again until I open the project again.


How do I upgrade the cordova-ios version that is integrated with Visual Studio?  This seems to be the underlying issue.   Surely someone at Microsoft has encountered this.

There should be some published way to keep the visual studio version of Cordova, the OSX version of Cordova and the XCode version in sync.

**Comment by TsunamiJohn** [comment]
cordova-ios 4.3.1 will NOT work.  In order to work with Xcode 8.3, I need cordova-ios 4.3.0 or greater.  You recommendation will not work because I have Xcode 8.3, therefore I need a more current version of cordova-ios than the one you are using.  As I have said, the version of OSX is installed and working and is new enough to work just fine with Xcode 8.3.   As I pointed out, if I changed the config.XML file on the VS side to use 7.0.1, then everything works, but each time I open the project, VS prompts to update the Cordova project and switches it back to cordova-ios 4.3.2 (which again, does not work).   I need Visual Studio to recognize a version of cordova-ios version 4.3.0 or greater.

 [By the way, your version of VS/Cordova is older than mine, as I have 4.3.2 on the VS side, while you have 4.3.1].

**Comment by rickmortensen** [comment]
Curious:  4.3.1 is > 4.3.0
Definitely fixed my problem when I received that error, and I definitely tried the steps you tried.

**Comment by TsunamiJohn** [comment]
Is there anyone on the Microsoft Cordova team that can comment on getting a cordova-ios version 4.3.0 or later supported inside VS 2017 15.3.2?

**Comment by BoiseBaked** [comment]
@TsunamiJohn, any luck on this issue? I'm having the exact same issue when I, from the VS2017 IDE, select the 'iOS' solutions platform and target: 'simulator - [any iOS device]'.

My Mac OS X env:
cordova -v: 7.1.0
remotebuild -v: Copyright (C) 2014-2015 Microsoft Corporation. All rights reserved. 2.1.3
MacOS High Sierra (10.13.1)
Xcode: 9.1

**Comment by DarrylLeckenby** [comment]
@BoiseBaked  @TsunamiJohn  Have either of you come across a solution for this yet?

I'm very close to re-writing a cordova app over to Xamarin because of the amount of issues related to the workstation tools I have trying to remote build with iOS from a windows workstation.

When I jump over to a mac workstation with Xamarin, I get a far better development experience targeting both iOS and Android. Cordova seems very problematic with iOS builds.

**Comment by BoiseBaked** [comment]
@DarrylLeckenby, I overcame this issue and others while attempting Cordova development on Windows 10 Pro using Visual Studio 2017. Honestly, Cordova development is easier on the Mac using node and the command-line. Even targeting Windows 10 UWP Cordova apps using Windows 10/VS2017 is problematic - crazy. But for the issue in this thread, see below for the short answer and the long answer.

**Comment by BoiseBaked** [comment]
Short answer: see: https://stackoverflow.com/questions/46202885/install-specific-version-of-cordova-cli-in-visual-studio-2017

Especially see this entry: "For iOS, please install iOS@4.3.1. This is the only version I found working with XCode 8.3.3"

**Comment by BoiseBaked** [comment]
The long answer:
MacOS X/Xcode: The tweaks required to build and deploy an iOS Cordova App, using Xcode on MacOS X to an iOS simulator or real device - all from Windows 10 Pro and VS 2017 using VS TACO:
	Before you start, don't forget to get the latest Xcode and Xcode command-line tools on your MacOS X platform. To install Xcode command-line tools: in MacOS X Terminal, type (w/out the single-quotes): 'xcode-select --install'
	Getting the Visual Studio 2017 IDE build to build to success, when targeting iOS solution platform and "Simulator - iPad Retina" device type (simulated device on MacOS X by-way-of Xcode), then start up remotebuild on MacOS X, in VS2017 IDE, select from Build menu, Build Solution or click the green play button (to the left of selected device):
		Encountered 3 "Remote build error from the build server https://Johns-MBP-4:3000/cordova" (as seen in the VS 2017 IDE):
			1. Build failed with error Remotebuild requires your projects to use cordova-ios 4.3.0 or greater with XCode 8.3. Please update your cordova-ios version.
			2. Build failed with error cordovaProject.projectConfig.getFileResources is not a function
			3. Build failed with error Warning: developmentTeam is missing from your build.json. See https://go.microsoft.com/fwlink/?linkid=833112 for more details.
		#1 caused by a future Xcode version not supported yet by VS2017 TACO. Solved by, on the Windows 10 PC, installing Cordova CLI latest (7.1.0), installing 'npm install -g cordova-ios@4.3.1' and removing and then re-adding Cordova iOS platform: "cordova platform add ios@4.3.1" using the previously selected version of the iOS Cordova platform. Using "cordova platform [rm|add] ios@latest," resulting in cordova-ios@4.5.4, definitely does not work. Here are the commands and what is seen after the ios platform add.
			From within the root directory of the project folder,
			Visual Studio Code command-line, execute:
			$ cordova platform rm ios
			$ cordova platform add ios@4.3.1

			stdout:
			Using cordova-fetch for cordova-ios@4.3.1
			Adding ios project...
			Creating Cordova project for the iOS platform:
			        Path: platforms\ios
			        Package: io.cordova.myappecee25
			        Name: BlankCordovaApp1
			iOS project created with cordova-ios@4.3.1
			Installing "cordova-plugin-inappbrowser" for ios
			Installing "cordova-plugin-whitelist" for ios
			--save flag or autosave detected
			Saving ios@~4.3.1 into config.xml file ...

		#2 results from doing 'npm install -g cordova-ios@latest" and then after "cordova platform add ios@latest," the result is cordova-ios@4.5.4, which doesn't work. Must use ios@4.3.1.
		#3 caused by new Xcode 8+ requirement for an Apple Developer Account's Team ID. To fix, add to build.json file within the VS 2017 project folder:
		"ios": {
		        "debug": {
		            "developmentTeam": "123456ABCD"
		},

		"release": {
		            "developmentTeam": "123456ABCD"
		}
		"123456ABCD" is my personal Apple Developer Account's Team ID (but now really). You can only get your developmentTeam (Apple Developer Account's Team) ID from online at your Apple developer's account.
	Note: when changing the cordova-ios platform version, when in the VS2017 app project folder, from the command-line, do global npm install first, 'npm install -g cordova-ios@4.3.1' followed by 'cordova platform rm ios' and then followed by 'cordova platform add ios@4.3.1.'
	If VS2017 fails to control and debug the simulated device on an MacOS X platform, via remotebuild, then with Xcode, open the VS2017 generated Xcode project found here on the MacOS X platform:
		/Users/[home directory]/.taco_home/remote-builds/taco-remote/builds/[some build number]/cordovaApp/platforms/ios/[project/app name in vs2017].xcodeproj
	To simulate any device with the given cordova app Xcode project, on very top roll of XCode, next to VS2017 project/app name, set "active scheme" to one of the "iOS Simulators" in list or to a connected iOS device.
	Click the "Build and then run the current scheme" (looks like a play button with triangle icon).
	You can also select the appropriate iOS Deployment Target (the iOS OS release - between iOS 9.3 and 11.1 in Xcode version 9.1)
	Note: using control-c to terminate the remotebuild webserver session causes all builds to be deleted. To keep a build, copy the "/Users/[home directory]/.taco_home/remote-builds/taco-remote/builds/[some build number]/cordovaApp/platforms/ios" folder elsewhere and rename "ios" to the app name. This becomes a standalone Xcode project folder.

**Comment by afxgroup** [comment]
use those two commands on mac:

sudo xcode-select -s /Applications/Xcode.app/Contents/Developer
sudo xcodebuild -license

on the second command accept the license file (hit more til the end and write agree)

**Comment by ouzs** [comment]
@rickmortensen Have you solved this problem? I have encountered the same problem now.

**Comment by ouzs** [comment]
@TsunamiJohn Have you solved this problem? I have encountered the same problem now.

**Comment by rickmortensen** [comment]
I followed @BoiseBaked suggestion and abandoned Visual Studio's integration with Cordova.  Because of some of the plug-ins we're using, I needed the latest (globally installed) Cordova version (8.1.2).  Thus on the Mac I use Cordova commands (within Terminal) to install needed plugins (if they aren't already installed).  Then I use either Xcode or Cordova command line to build the app.  Because I'm no longer using VS to "copy app source to the Mac JIT", I use Mac Finder to Go...Open Shared folder - to access my shared TFS source code.

**Comment by mb34124** [comment]
@ouzs  Like @rickmortensen I bailed on VS integration with Cordova.  Instead I use VS Code and the terminal on a Mac.

**Comment by speige** [comment]
The answer from boisebaked fixed it for me.

Short version:
```
npm install -g cordova-ios@4.3.1
cordova platform rm ios
cordova platform add ios@4.3.1
```
